title: Emile Van Der Heyde # your name (or website title) here
logo: "/images/me_map.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I have a passion and aptitude for problem-solving and data science. I have upskilled myself in Python programming writing programs to shape and extract data from structured and unstructured data sources.
Going forward I want to be involved in the pioneering analysis of a new product or area of business, creating new views, variables, and data tools. I would like to work with Python as I would like to grow my skill set in learning new techniques in machine learning.
I am also interested in improving my skills in how to sell analysis ideas effectively as well as finance levers that drive business.  
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/emilevdheyde/">View My LinkedIn Profile</a> 
  
theme: minima
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
